// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // 为Otto DIY网站定义侧边栏结构，只包含已创建的页面
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: '项目介绍',
    },
    {
      type: 'doc',
      id: 'getting-started',
      label: '入门指南',
    },
    {
      type: 'doc',
      id: 'pcb-order',
      label: 'PCB下单',
    },
    {
      type: 'doc',
      id: 'bom',
      label: '零部件清单',
    },
    {
      type: 'doc',
      id: 'downloads',
      label: '程序下载',
    },
    {
      type: 'doc',
      id: 'assembly',
      label: '组装教程',
    },
    {
      type: 'doc',
      id: 'usage',
      label: '使用说明',
    },
    {
      type: 'doc',
      id: 'faq',
      label: '常见问题',
    },
    // 后续可继续添加更多页面
  ],

  // By default, Docusaurus generates a sidebar from the docs folder structure
  /*
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
   */
};

export default sidebars;
